import { createAccount, createClient } from 'https://esm.sh/genlayer-js@1.1.8';
import { studionet } from 'https://esm.sh/genlayer-js@1.1.8/chains';
const CONTRACT='0xa7DF3c951D0Cf2D625027d8b5F16d339cD815174',ENDPOINT='https://studio.genlayer.com/api';
const reader=createClient({chain:studionet,endpoint:ENDPOINT,account:createAccount()});let wallet,account;
const byId=id=>document.getElementById(id),value=id=>(byId(id)?.value||'').trim();
document.querySelector(`[data-nav="${document.body.dataset.page}"]`)?.setAttribute('aria-current','page');
const remember=id=>{if(id)localStorage.setItem('signal-tribunal-case',id)};
const recalled=()=>new URLSearchParams(location.search).get('case')||localStorage.getItem('signal-tribunal-case')||'';
document.querySelectorAll('[data-case-id]').forEach(el=>{if(!el.value)el.value=recalled()});
function setStatus(message,tone=''){const box=byId('status');if(!box)return;box.classList.remove('hidden');box.dataset.tone=tone;box.querySelector('[data-status-text]').textContent=message;box.scrollIntoView({behavior:'smooth',block:'nearest'})}
function explainError(e){const raw=e?.shortMessage||e?.message||String(e);if(/rejected|denied/i.test(raw))return'The wallet request was cancelled. No transaction was sent.';if(/resolution not found/i.test(raw))return'No case was found with that ID. Check the spelling and try again.';if(/challenge window closed/i.test(raw))return'This case is outside its challenge window.';if(/independent challenge host/i.test(raw))return'The challenge source must use a hostname different from both original sources.';return raw}
async function connect(){if(!window.ethereum)throw Error('A browser wallet such as MetaMask or Rabby is required for this action.');[account]=await window.ethereum.request({method:'eth_requestAccounts'});if(String(await window.ethereum.request({method:'eth_chainId'})).toLowerCase()!=='0xf22f')await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0xf22f'}]});wallet=createClient({chain:studionet,endpoint:ENDPOINT,account,provider:window.ethereum});document.querySelectorAll('[data-wallet]').forEach(el=>el.textContent=`${account.slice(0,6)}…${account.slice(-4)}`);setStatus(`Wallet connected: ${account}`,'success');return wallet}
async function readCase(id){if(!id)throw Error('Enter a case ID first.');remember(id);setStatus(`Looking up ${id} on StudioNet…`);return reader.readContract({address:CONTRACT,functionName:'get_resolution',args:[id]})}
function links(values){const wrap=document.createElement('span');values.forEach((url,i)=>{if(i)wrap.append(document.createElement('br'));const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noreferrer';a.textContent=url;wrap.append(a)});return wrap}
function row(label,content){const item=document.createElement('div');item.className='record-row';const name=document.createElement('b');name.textContent=label;const body=content instanceof Node?content:document.createElement('span');if(!(content instanceof Node))body.textContent=String(content??'—');item.append(name,body);return item}
function renderRecord(data){const box=byId('status');box.classList.remove('hidden');box.dataset.tone='success';box.querySelector('[data-status-text]').textContent='Live canonical contract state';const record=byId('record');record.replaceChildren();const state=document.createElement('span');state.className='state-pill';state.textContent=data.state;record.append(row('Case ID',data.id),row('State',state),row('Question',data.question),row('Choices',(data.choices||[]).join(' · ')),row('Ruling',data.answer||'Not assessed yet'),row('Findings',(data.findings||[]).join(' · ')||'None yet'),row('Sources',links(data.sources||[])));if(data.challengeSource)record.append(row('Challenge source',links([data.challengeSource])));record.append(row('Content digests',(data.digests||[]).join('\n')||'Created when validators assess the evidence'));if(Number(data.challengeEnd))record.append(row('Challenge deadline',new Date(Number(data.challengeEnd)*1000).toLocaleString()))}
async function transact(functionName,args,caseId){try{if(!wallet)await connect();setStatus('Step 1 of 3 · Check the details in your wallet. Nothing is final yet.');const hash=await wallet.writeContract({address:CONTRACT,functionName,args,value:0n});setStatus(`Step 2 of 3 · Transaction submitted: ${hash}\nWaiting for validator finalization…`);await wallet.waitForTransactionReceipt({hash,status:'FINALIZED',retries:180,interval:5000});setStatus(`Step 3 of 3 · Transaction finalized: ${hash}`,'success');renderRecord(await readCase(caseId))}catch(e){setStatus(explainError(e),'error')}}
byId('connect')?.addEventListener('click',()=>connect().catch(e=>setStatus(explainError(e),'error')));
byId('lookup-form')?.addEventListener('submit',async e=>{e.preventDefault();try{renderRecord(await readCase(value('case-id')))}catch(x){setStatus(explainError(x),'error')}});
byId('file-form')?.addEventListener('submit',e=>{e.preventDefault();const id=value('case-id'),choices=value('choices').split(',').map(x=>x.trim()).filter(Boolean);if(choices.length<2)return setStatus('Provide at least two comma-separated choices.','error');try{if(new URL(value('source-a')).hostname===new URL(value('source-b')).hostname)return setStatus('The two evidence sources must use different hostnames.','error')}catch{return setStatus('Both evidence sources must be valid HTTPS URLs.','error')}remember(id);transact('propose',[id,value('question'),choices,[value('source-a'),value('source-b')],Number(value('window'))],id)});
byId('assess')?.addEventListener('click',()=>{const id=value('case-id');if(!id)return setStatus('Enter a case ID first.','error');remember(id);transact('assess',[id,Number(value('window'))],id)});
byId('finalize')?.addEventListener('click',()=>{const id=value('case-id');if(!id)return setStatus('Enter a case ID first.','error');remember(id);transact('finalize',[id],id)});
byId('challenge-form')?.addEventListener('submit',e=>{e.preventDefault();const id=value('case-id');remember(id);transact('challenge',[id,value('challenge-source')],id)});
